### ISSUE TITLE
[RFC] Conventions de codage

### ISSUE THREAD

**Issue by ooflorent** [EsupPortail/esup-commons-core#10]
D'après le [changelog](http://www.esup-portail.org/display/PROJCOMMONS/Changelog), il est prévu de :

> Revoir le checkStyle d'esup-commons pour eclipse Indigo

Je me propose donc pour effectuer cette tâche. L'objectif est de produire un fichier checkStyle et de reformater l'intégralité du code d'ECV2 conformément à celui-ci. Je profite de ce moment car aucune PR n'est attente (donc pas de merge).

**Comment by raymondBourges** [comment]
Je ne suis jamais contre une contribution !
Par contre concernant checkStyle, je me pose toujours la question de savoir si on peut avoir une conf qui convienne à 100% des contributeurs.
NB : Cette question est suscitée par ma faible expérience de checkStyle et est peut-être hors de propos.
Je suis preneur de ton retour d'expérience avant de te dire d'y aller.
Merci

**Comment by ooflorent** [comment]
Personnellement je me sers peu de Checkstyle. Il m'est surtout utile afin de m'assurer que les annotations telles que `@Override` ou `@Deprecated` sont présentes dans le code, ainsi que pour vérifier que les variables soient correctement nommées.

Afin de proposer un _kit_ complet aux développeurs concernant les conventions de codage, je pensais que nous pourrions aussi distribuer une configuration pour le formateur de code d'Eclipse (fichier XML).

> Par contre concernant checkStyle, je me pose toujours la question de savoir si on peut avoir une conf qui convienne à 100% des contributeurs.

C'est justement l'intérêt de mettre en place des conventions de codage ! Aujourd'hui quand on regarde le code d'ECV2, on pourrait presque identifier le contributeur tellement le style visuel diffère d'une classe à l'autre. En uniformisant le style employé, certains vont avoir du mal à prendre de nouvelles habitudes, c'est évidant. Toutefois, afin d'améliorer la lecture du code (et donc sa compréhension), je pense qu'il s'agit d'un mal nécessaire.

**Comment by raymondBourges** [comment]
Donc que proposes-tu ? J'ai un peu de mal à voir.
Une conf Checkstyle minimale et (?) une conf eclipse ?
Merci

**Comment by ooflorent** [comment]
Tout à fait.

Il s'agirait d'un ensemble de fichiers de configurations comportant :
- fichier Checkstyle (pour s'assurer que les conventions de nommage soient respectées)
- configuration pour le formateur de code (pour s'assurer que les accolades soient correctement positionnées, par exemple)
- configuration pour l'ordre des imports
- configuration pour les tâches automatiques lors de la sauvegarde (_trim_ des lignes par exemple)

**Comment by raymondBourges** [comment]
Ok je vois mieux.

Tu avances dans ce sens alors ?

**Comment by ooflorent** [comment]
Je viens de faire un premier test de formatage (très proche de celui que j'applique au quotidien). Je ne l'ai appliqué que sur `annotations`, `auth` et une partie de `core`. Si de telles conventions peuvent convenir, je mettrais à disposition ma configuration et l'appliquerais pour l'ensemble des projets.

Il est consultable sur ooflorent/esup-commons-core@2f4024d799cdb426877097493ac034f6d784c945

**Comment by ooflorent** [comment]
Serait-il possible d'avoir un retour ?

**Comment by raymondBourges** [comment]
Le diff gitHub ne permet pas de bien juger de ce qui est réellement fait :-(

Tu peux expliquer un peu : 
- Quelles configs as-tu fait ? --> Comment sont-elles utilisables par les autres développeurs (fichier de conf à installer dans eclipse ? conf maven ?) --> En effet, si on n'arrive pas à se partager FACILEMENT cet outillage on aura toujours un code mal reformater par l'un ou l'autre
- Quel impact au final dans le code ?

Merci

**Comment by ooflorent** [comment]
> Le diff gitHub ne permet pas de bien juger de ce qui est réellement fait :-(

Il suffit d'ajouter le paramètre `?w=0` à l'URL pour y voir plus clair !

Je viens de créer un [gist](https://gist.github.com/3986895) afin de partager les fichiers de configuration.
Ces fichiers doivent être importés de la manière suivante depuis Eclipse :
-  `checkstyle.xml`: Preferences > Checkstyle > New
- `checkup.xml`: Preferences > Java > Code Style > Clean Up > Import...
- `formatter.xml`: Preferences > Java > Code Style > Formatter > Import...
- `checkup.xml`: Preferences > Java > Code Style > Organize Imports > Import...

Ces fichiers peuvent être partagés directement depuis Esup-Portail. Afin de s'assurer que les standards sont appliqués, il suffit de contrôler le code avant de le merger (une simple revue est suffisant).
